# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Twenty Ten"
license = "MIT"
licenselink = "https://github.com/hzmangel/hugo-twenty-ten/blob/master/LICENSE.md"
description = "WP theme Twenty Ten for Hugo"
homepage = "http://hzmangel.github.io"
tags = ["Wordpress"]
features = []
min_version = 0.13

[author]
  name = "hzmangel"
  homepage = "http://hzmangel.github.io"

[original]
  name = "Twenty Ten"
  homepage = "https://wordpress.org/themes/twentyten/"
  repo = "https://themes.trac.wordpress.org/browser/twentyten/"
